### ISSUE TITLE
Dropdown Bug

### ISSUE THREAD

**Issue by iraklikvachantiradze** [logiqsystem/admin4b#64] opened 2019-02-13 14:15 UTC
I've added bootstrap dropdown button and it doesn't work. please, can you help me?

**Comment by marxjmoura** [comment] 2019-02-16 14:07
Hi @iraklikvachantiradze. Please give some details. I appreciate if you can share this part of the HTML code or a screenshot so I can understand what's going on.

**Comment by iraklikvachantiradze** [comment] 2019-02-18 08:51
> Hi @iraklikvachantiradze. Please give some details. I appreciate if you can share this part of the HTML code or a screenshot so I can understand what's going on.

Hello,  when I've included only admin4b.min.js and put bootstrap dropdown button in html, It doesn't make dropdown when I click the button. Then I've included bootstrap.js and the dropdown works only at first click. After that it doesn't work if I don't refresh the page.
[screenshot] (https://prnt.sc/mmk7lt)

**Comment by marxjmoura** [comment] 2019-02-18 12:47
Thank you, @iraklikvachantiradze. I have done some tests for common cases but I could not reproduce the problem you are experiencing.

I am sharing with you the code I used during my tests, please, save to a file (e.g. `index.html`) and run it in your browser. Then add the CSS and JS you are using until you find what is breaking the dropdown. So we continue from there.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://getadmin4b.com/dist/admin4b.min.css" rel="stylesheet">
</head>
<body>
  <div class="app">
    <div class="app-content">
      <div class="content-body">
        <div class="container">
          <!-- Dropdown button -->
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown button
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
          <!-- Dropdown inside a card -->
          <div class="card mt-3">
            <div class="card-header">
              Dropdown
            </div>
            <div class="card-body">
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown button
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </div>
            </div>
          </div>
          <!-- Dropdown inside a table -->
          <div class="card mt-3">
            <div class="card-header">
              Dropdown
            </div>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Item</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Item 1</td>
                    <td>
                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown button
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>Item 2</td>
                    <td>
                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown button
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://getadmin4b.com/dist/admin4b.min.js"></script>
</body>
</html>
```

**Comment by iraklikvachantiradze** [comment] 2019-02-19 11:49
I had the old admin4b.min.js file in my project. Now I've downloaded version 2.0.0 and it works! Thanks.

**Comment by marxjmoura** [comment] 2019-02-19 13:50
Great to know that! Remember to read our [CHANGELOG](https://github.com/logiqsystem/admin4b/blob/master/CHANGELOG.md) to know about the breaking changes ok?

@iraklikvachantiradze I'm closing this issue. Feel free to open a new issue if you need help with the new version.

**Closed by marxjmoura** 2019-02-19 13:50 UTC
Labels: help wanted
